### ISSUE TITLE
Doesn't work in Rails 4.1+

### ISSUE THREAD

**Issue by kartikluke** [Vermonster/copycat#22]
Getting the "undefined method `attr_accessible' for #<Class:0x007fa32ee13ab0>" error as we need to use strong parameters.
